#!/bin/sh

#################################################################################
#
#   Lynis
# ------------------
#
# Copyright 2007-2016, Michael Boelen, CISOfy (michael.boelen@cisofy.com)
# Web site: https://cisofy.com
#
# Lynis comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Some custom include we user for development and testing.
#
# Added:
# - PAM Tally
#
#################################################################################
#
    InsertSection "[Development] Checks for pentesting"
#
#################################################################################
#
  # Test        : DEV-9900
	# Author      : Tom van Ommen <info@tomvanommen.nl>
  # Description : Detection of failed login attempts
	# Notes       : pam_tally - The login counter (tallying) module

    Register --test-no DEV-9900 --weight L --network NO --description "Checking presence of tally login attempt counter (PAM)"
    if [ ${SKIPTEST} -eq 0 ]; then
        FOUND=0
        FOUND_TALLY=0
        FOUND_TALLY2=0	
	
        # tally
        LogText "Searching tally PAM module"
        for I in ${PAM_FILE_LOCATIONS}; do
            if [ -f ${I}/pam_tally.so ]; then
                FOUND_TALLY=1
                LogText "Result: found pam_tally.so (tally library PAM) in ${I}"
            fi
        done
        if [ ${FOUND_TALLY} -eq 1 ]; then
            LogText "Result: pam_tally.so found"
            Report "pam_tallylib=1"
            AddHP 3 3
            FOUND=1
          else
            LogText "Result: pam_tally.so NOT found (tally library PAM)"
            AddHP 1 3
        fi

        # tally2
        LogText "Searching tally2 PAM module"
        for I in ${PAM_FILE_LOCATIONS}; do
            if [ -f ${I}/pam_tally2.so ]; then	
                FOUND_TALLY2=1
                LogText "Result: found pam_tally2.so (tally2 library PAM) in ${I}"
            fi
        done
        if [ ${FOUND_TALLY2} -eq 1 ]; then
            LogText "Result: pam_tally2.so found"
            Report "pam_tally2lib=1"
            AddHP 3 3
            FOUND=1
          else
            LogText "Result: pam_tally2.so NOT found (tally2 library PAM)"
            AddHP 1 3
        fi
	fi
		
#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# Lynis - Copyright 2007-2016, Michael Boelen, CISOfy - https://cisofy.com
